arb-dir: lib/l10n/arbs
template-arb-file: app_en.arb
output-dir: lib/l10n/generated
output-localization-file: app_localizations.dart
untranslated-messages-file: temp/l10n_errors.txt
nullable-getter: false
